version: "3"
services:
  traffix-postgres:
    image: postgres:17.0-alpine
    container_name: traffix-postgres
    restart: unless-stopped
    expose:
      - "${POSTGRES_PORT}"
    env_file: .env
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - default
    logging:
      options:
        max-size: "50m"
