version: '3'
services:
  
  traffix-front:
    container_name: traffix-front
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile.front
      context: ./
      args:
        VITE_NODE_ENV: ${VITE_NODE_ENV}
    expose:
      - ${VITE_FRONT_PORT}
    env_file: .env
    volumes:
     - ./front/src:/usr/src/app/front/src
    networks:
      - default
    logging:
        options:
          max-size: '50m'

