version: '3'
services:

  traffix-nginx:
    image: nginx:1.27.1
    container_name: traffix-nginx
    restart: unless-stopped
    entrypoint: 
      - ./entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - 80:80
      - 443:443
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: .env
    volumes:     
      - ./nginx/${VITE_NODE_ENV}.nginx.conf:/etc/nginx/templates/default.conf.template
      - ./nginx/stream.nginx.conf:/etc/nginx/templates/stream.conf.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./certbot/www/:/var/www/certbot
      - ./certbot/conf/:/etc/letsencrypt
      - ./front/dist:/dist
    networks:
      - default
    depends_on:
      - traffix-front
      - traffix-back
      - traffix-postgres
      - traffix-init-dhparams
      - traffix-certbot-oneshot
    logging:
        options:
          max-size: '50m'

