version: '3'
services:

  traffix-blockchain:
    container_name: traffix-blockchain
    build:
      dockerfile: ./Dockerfile.blockchain
      context: ./
      args:
        VITE_NODE_ENV: ${VITE_NODE_ENV}
    expose:
      - ${VITE_BLOCKCHAIN_APP_PORT}
    restart: unless-stopped
    env_file: .env
    networks:
      - default
    depends_on:
      - traffix-postgres
      - traffix-back
    logging:
        options:
          max-size: '50m'
    develop:
      watch:
        - action: sync
          path: ./blockchain/src
          target: /usr/src/app/blockchain
          ignore: 
            - ./blockchain/node_modules/
        - action: rebuild
          path: ./blockchain/package.json

